/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AttendanceMethod = { 'qrScan' : null } |
  { 'manualEntry' : null } |
  { 'autoCheckout' : null };
export interface AttendanceRecord {
  'status' : string,
  'memberId' : string,
  'method' : AttendanceMethod,
  'checkInTime' : Time,
  'checkOutTime' : [] | [Time],
}
export type CreateMemberResult = { 'missingField' : { 'fieldName' : string } } |
  { 'duplicateContactInfo' : null } |
  { 'agentError' : string } |
  { 'notFound' : { 'id' : string, 'entity' : string } } |
  { 'success' : null };
export interface DietChart {
  'id' : string,
  'meals' : Array<Meal>,
  'name' : string,
  'description' : string,
}
export interface Exercise {
  'name' : string,
  'reps' : bigint,
  'sets' : bigint,
  'instructions' : string,
}
export type ExternalBlob = Uint8Array;
export interface LocationCoordinates {
  'latitude' : number,
  'longitude' : number,
}
export interface Meal {
  'carbs' : bigint,
  'fats' : bigint,
  'calories' : bigint,
  'name' : string,
  'description' : string,
  'protein' : bigint,
}
export interface MemberProfile {
  'id' : string,
  'finalPayableAmount' : bigint,
  'status' : MembershipStatus,
  'contactInfo' : string,
  'assignedWorkoutId' : [] | [string],
  'assignedDietId' : [] | [string],
  'discountAmount' : bigint,
  'name' : string,
  'membershipStart' : Time,
  'membershipEnd' : Time,
  'packageId' : string,
}
export interface MembershipPackage {
  'id' : string,
  'packageType' : string,
  'durationInMonths' : bigint,
  'priceInRupees' : bigint,
}
export type MembershipStatus = { 'active' : null } |
  { 'inactive' : null } |
  { 'paused' : null };
export interface PauseRequest {
  'id' : string,
  'status' : PauseRequestStatus,
  'memberId' : string,
  'processedAt' : [] | [Time],
  'adminMessage' : [] | [string],
  'requestedAt' : Time,
}
export type PauseRequestStatus = { 'expired' : null } |
  { 'pending' : null } |
  { 'denied' : null } |
  { 'approved' : null };
export type Time = bigint;
export interface UserProfile {
  'memberId' : [] | [string],
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoMetadata {
  'id' : string,
  'associatedWorkoutId' : [] | [string],
  'title' : string,
  'blob' : ExternalBlob,
  'description' : string,
  'category' : string,
}
export interface WorkoutChart {
  'id' : string,
  'name' : string,
  'exercises' : Array<Exercise>,
  'description' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addVideo' : ActorMethod<[VideoMetadata], undefined>,
  'approvePauseRequest' : ActorMethod<[string, [] | [string]], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDietChart' : ActorMethod<[DietChart], undefined>,
  'createMember' : ActorMethod<[MemberProfile], CreateMemberResult>,
  'createMembershipPackage' : ActorMethod<[MembershipPackage], undefined>,
  'createWorkoutChart' : ActorMethod<[WorkoutChart], undefined>,
  'deleteMembershipPackage' : ActorMethod<[string], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'denyPauseRequest' : ActorMethod<[string, [] | [string]], undefined>,
  'getAllDietCharts' : ActorMethod<[], Array<DietChart>>,
  'getAllMembers' : ActorMethod<[], Array<MemberProfile>>,
  'getAllMembershipPackages' : ActorMethod<[], Array<MembershipPackage>>,
  'getAllPauseRequests' : ActorMethod<[], Array<PauseRequest>>,
  'getAllWorkoutCharts' : ActorMethod<[], Array<WorkoutChart>>,
  'getAssignedDiet' : ActorMethod<[string], DietChart>,
  'getAssignedWorkout' : ActorMethod<[string], WorkoutChart>,
  'getAttendanceHistory' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentCheckInStatus' : ActorMethod<
    [string],
    [] | [
      {
        'method' : [] | [AttendanceMethod],
        'checkInTime' : [] | [Time],
        'isCheckedIn' : boolean,
      }
    ]
  >,
  'getGymLocation' : ActorMethod<
    [],
    { 'radius' : bigint, 'location' : LocationCoordinates }
  >,
  'getMemberByContactInfo' : ActorMethod<[string], [] | [MemberProfile]>,
  'getMemberProfile' : ActorMethod<[string], MemberProfile>,
  'getPauseRequestStatus' : ActorMethod<
    [string],
    [] | [
      {
        'status' : PauseRequestStatus,
        'requestId' : string,
        'adminMessage' : [] | [string],
      }
    ]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoLibrary' : ActorMethod<[string], Array<VideoMetadata>>,
  'hasPendingPauseRequest' : ActorMethod<[string], boolean>,
  'healthCheck' : ActorMethod<
    [],
    { 'ok' : boolean, 'version' : string, 'timestamp' : Time }
  >,
  'initiatePauseRequest' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'processAutoCheckout' : ActorMethod<[string], undefined>,
  'recordAttendance' : ActorMethod<[AttendanceRecord], undefined>,
  'recordQRAttendance' : ActorMethod<[string, boolean], undefined>,
  'resumeMembership' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDietChart' : ActorMethod<[DietChart], undefined>,
  'updateGymLocation' : ActorMethod<[LocationCoordinates, bigint], undefined>,
  'updateMember' : ActorMethod<[MemberProfile], undefined>,
  'updateMembershipPackage' : ActorMethod<[MembershipPackage], undefined>,
  'updateWorkoutChart' : ActorMethod<[WorkoutChart], undefined>,
  'validateMemberLogin' : ActorMethod<[string], { 'isValid' : boolean }>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];