/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const VideoMetadata = IDL.Record({
  'id' : IDL.Text,
  'associatedWorkoutId' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Meal = IDL.Record({
  'carbs' : IDL.Nat,
  'fats' : IDL.Nat,
  'calories' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'protein' : IDL.Nat,
});
export const DietChart = IDL.Record({
  'id' : IDL.Text,
  'meals' : IDL.Vec(Meal),
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const MembershipStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
  'paused' : IDL.Null,
});
export const Time = IDL.Int;
export const MemberProfile = IDL.Record({
  'id' : IDL.Text,
  'finalPayableAmount' : IDL.Nat,
  'status' : MembershipStatus,
  'contactInfo' : IDL.Text,
  'assignedWorkoutId' : IDL.Opt(IDL.Text),
  'assignedDietId' : IDL.Opt(IDL.Text),
  'discountAmount' : IDL.Nat,
  'name' : IDL.Text,
  'membershipStart' : Time,
  'membershipEnd' : Time,
  'packageId' : IDL.Text,
});
export const CreateMemberResult = IDL.Variant({
  'missingField' : IDL.Record({ 'fieldName' : IDL.Text }),
  'duplicateContactInfo' : IDL.Null,
  'agentError' : IDL.Text,
  'notFound' : IDL.Record({ 'id' : IDL.Text, 'entity' : IDL.Text }),
  'success' : IDL.Null,
});
export const MembershipPackage = IDL.Record({
  'id' : IDL.Text,
  'packageType' : IDL.Text,
  'durationInMonths' : IDL.Nat,
  'priceInRupees' : IDL.Nat,
});
export const Exercise = IDL.Record({
  'name' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'instructions' : IDL.Text,
});
export const WorkoutChart = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'exercises' : IDL.Vec(Exercise),
  'description' : IDL.Text,
});
export const PauseRequestStatus = IDL.Variant({
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'denied' : IDL.Null,
  'approved' : IDL.Null,
});
export const PauseRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : PauseRequestStatus,
  'memberId' : IDL.Text,
  'processedAt' : IDL.Opt(Time),
  'adminMessage' : IDL.Opt(IDL.Text),
  'requestedAt' : Time,
});
export const AttendanceMethod = IDL.Variant({
  'qrScan' : IDL.Null,
  'manualEntry' : IDL.Null,
  'autoCheckout' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'status' : IDL.Text,
  'memberId' : IDL.Text,
  'method' : AttendanceMethod,
  'checkInTime' : Time,
  'checkOutTime' : IDL.Opt(Time),
});
export const UserProfile = IDL.Record({
  'memberId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const LocationCoordinates = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addVideo' : IDL.Func([VideoMetadata], [], []),
  'approvePauseRequest' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDietChart' : IDL.Func([DietChart], [], []),
  'createMember' : IDL.Func([MemberProfile], [CreateMemberResult], []),
  'createMembershipPackage' : IDL.Func([MembershipPackage], [], []),
  'createWorkoutChart' : IDL.Func([WorkoutChart], [], []),
  'deleteMembershipPackage' : IDL.Func([IDL.Text], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'denyPauseRequest' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'getAllDietCharts' : IDL.Func([], [IDL.Vec(DietChart)], ['query']),
  'getAllMembers' : IDL.Func([], [IDL.Vec(MemberProfile)], ['query']),
  'getAllMembershipPackages' : IDL.Func(
      [],
      [IDL.Vec(MembershipPackage)],
      ['query'],
    ),
  'getAllPauseRequests' : IDL.Func([], [IDL.Vec(PauseRequest)], ['query']),
  'getAllWorkoutCharts' : IDL.Func([], [IDL.Vec(WorkoutChart)], ['query']),
  'getAssignedDiet' : IDL.Func([IDL.Text], [DietChart], ['query']),
  'getAssignedWorkout' : IDL.Func([IDL.Text], [WorkoutChart], ['query']),
  'getAttendanceHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentCheckInStatus' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'method' : IDL.Opt(AttendanceMethod),
            'checkInTime' : IDL.Opt(Time),
            'isCheckedIn' : IDL.Bool,
          })
        ),
      ],
      ['query'],
    ),
  'getGymLocation' : IDL.Func(
      [],
      [IDL.Record({ 'radius' : IDL.Nat, 'location' : LocationCoordinates })],
      ['query'],
    ),
  'getMemberByContactInfo' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MemberProfile)],
      ['query'],
    ),
  'getMemberProfile' : IDL.Func([IDL.Text], [MemberProfile], ['query']),
  'getPauseRequestStatus' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'status' : PauseRequestStatus,
            'requestId' : IDL.Text,
            'adminMessage' : IDL.Opt(IDL.Text),
          })
        ),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoLibrary' : IDL.Func([IDL.Text], [IDL.Vec(VideoMetadata)], ['query']),
  'hasPendingPauseRequest' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'healthCheck' : IDL.Func(
      [],
      [
        IDL.Record({
          'ok' : IDL.Bool,
          'version' : IDL.Text,
          'timestamp' : Time,
        }),
      ],
      ['query'],
    ),
  'initiatePauseRequest' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'processAutoCheckout' : IDL.Func([IDL.Text], [], []),
  'recordAttendance' : IDL.Func([AttendanceRecord], [], []),
  'recordQRAttendance' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'resumeMembership' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDietChart' : IDL.Func([DietChart], [], []),
  'updateGymLocation' : IDL.Func([LocationCoordinates, IDL.Nat], [], []),
  'updateMember' : IDL.Func([MemberProfile], [], []),
  'updateMembershipPackage' : IDL.Func([MembershipPackage], [], []),
  'updateWorkoutChart' : IDL.Func([WorkoutChart], [], []),
  'validateMemberLogin' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'isValid' : IDL.Bool })],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const VideoMetadata = IDL.Record({
    'id' : IDL.Text,
    'associatedWorkoutId' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Meal = IDL.Record({
    'carbs' : IDL.Nat,
    'fats' : IDL.Nat,
    'calories' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'protein' : IDL.Nat,
  });
  const DietChart = IDL.Record({
    'id' : IDL.Text,
    'meals' : IDL.Vec(Meal),
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const MembershipStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
    'paused' : IDL.Null,
  });
  const Time = IDL.Int;
  const MemberProfile = IDL.Record({
    'id' : IDL.Text,
    'finalPayableAmount' : IDL.Nat,
    'status' : MembershipStatus,
    'contactInfo' : IDL.Text,
    'assignedWorkoutId' : IDL.Opt(IDL.Text),
    'assignedDietId' : IDL.Opt(IDL.Text),
    'discountAmount' : IDL.Nat,
    'name' : IDL.Text,
    'membershipStart' : Time,
    'membershipEnd' : Time,
    'packageId' : IDL.Text,
  });
  const CreateMemberResult = IDL.Variant({
    'missingField' : IDL.Record({ 'fieldName' : IDL.Text }),
    'duplicateContactInfo' : IDL.Null,
    'agentError' : IDL.Text,
    'notFound' : IDL.Record({ 'id' : IDL.Text, 'entity' : IDL.Text }),
    'success' : IDL.Null,
  });
  const MembershipPackage = IDL.Record({
    'id' : IDL.Text,
    'packageType' : IDL.Text,
    'durationInMonths' : IDL.Nat,
    'priceInRupees' : IDL.Nat,
  });
  const Exercise = IDL.Record({
    'name' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'instructions' : IDL.Text,
  });
  const WorkoutChart = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'exercises' : IDL.Vec(Exercise),
    'description' : IDL.Text,
  });
  const PauseRequestStatus = IDL.Variant({
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'denied' : IDL.Null,
    'approved' : IDL.Null,
  });
  const PauseRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : PauseRequestStatus,
    'memberId' : IDL.Text,
    'processedAt' : IDL.Opt(Time),
    'adminMessage' : IDL.Opt(IDL.Text),
    'requestedAt' : Time,
  });
  const AttendanceMethod = IDL.Variant({
    'qrScan' : IDL.Null,
    'manualEntry' : IDL.Null,
    'autoCheckout' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'status' : IDL.Text,
    'memberId' : IDL.Text,
    'method' : AttendanceMethod,
    'checkInTime' : Time,
    'checkOutTime' : IDL.Opt(Time),
  });
  const UserProfile = IDL.Record({
    'memberId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const LocationCoordinates = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addVideo' : IDL.Func([VideoMetadata], [], []),
    'approvePauseRequest' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDietChart' : IDL.Func([DietChart], [], []),
    'createMember' : IDL.Func([MemberProfile], [CreateMemberResult], []),
    'createMembershipPackage' : IDL.Func([MembershipPackage], [], []),
    'createWorkoutChart' : IDL.Func([WorkoutChart], [], []),
    'deleteMembershipPackage' : IDL.Func([IDL.Text], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'denyPauseRequest' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'getAllDietCharts' : IDL.Func([], [IDL.Vec(DietChart)], ['query']),
    'getAllMembers' : IDL.Func([], [IDL.Vec(MemberProfile)], ['query']),
    'getAllMembershipPackages' : IDL.Func(
        [],
        [IDL.Vec(MembershipPackage)],
        ['query'],
      ),
    'getAllPauseRequests' : IDL.Func([], [IDL.Vec(PauseRequest)], ['query']),
    'getAllWorkoutCharts' : IDL.Func([], [IDL.Vec(WorkoutChart)], ['query']),
    'getAssignedDiet' : IDL.Func([IDL.Text], [DietChart], ['query']),
    'getAssignedWorkout' : IDL.Func([IDL.Text], [WorkoutChart], ['query']),
    'getAttendanceHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentCheckInStatus' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'method' : IDL.Opt(AttendanceMethod),
              'checkInTime' : IDL.Opt(Time),
              'isCheckedIn' : IDL.Bool,
            })
          ),
        ],
        ['query'],
      ),
    'getGymLocation' : IDL.Func(
        [],
        [IDL.Record({ 'radius' : IDL.Nat, 'location' : LocationCoordinates })],
        ['query'],
      ),
    'getMemberByContactInfo' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MemberProfile)],
        ['query'],
      ),
    'getMemberProfile' : IDL.Func([IDL.Text], [MemberProfile], ['query']),
    'getPauseRequestStatus' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'status' : PauseRequestStatus,
              'requestId' : IDL.Text,
              'adminMessage' : IDL.Opt(IDL.Text),
            })
          ),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoLibrary' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(VideoMetadata)],
        ['query'],
      ),
    'hasPendingPauseRequest' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'healthCheck' : IDL.Func(
        [],
        [
          IDL.Record({
            'ok' : IDL.Bool,
            'version' : IDL.Text,
            'timestamp' : Time,
          }),
        ],
        ['query'],
      ),
    'initiatePauseRequest' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'processAutoCheckout' : IDL.Func([IDL.Text], [], []),
    'recordAttendance' : IDL.Func([AttendanceRecord], [], []),
    'recordQRAttendance' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'resumeMembership' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDietChart' : IDL.Func([DietChart], [], []),
    'updateGymLocation' : IDL.Func([LocationCoordinates, IDL.Nat], [], []),
    'updateMember' : IDL.Func([MemberProfile], [], []),
    'updateMembershipPackage' : IDL.Func([MembershipPackage], [], []),
    'updateWorkoutChart' : IDL.Func([WorkoutChart], [], []),
    'validateMemberLogin' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'isValid' : IDL.Bool })],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };