/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Meal {
    carbs: bigint;
    fats: bigint;
    calories: bigint;
    name: string;
    description: string;
    protein: bigint;
}
export interface Exercise {
    name: string;
    reps: bigint;
    sets: bigint;
    instructions: string;
}
export type Time = bigint;
export interface LocationCoordinates {
    latitude: number;
    longitude: number;
}
export interface WorkoutChart {
    id: string;
    name: string;
    exercises: Array<Exercise>;
    description: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PauseRequest {
    id: string;
    status: PauseRequestStatus;
    memberId: string;
    processedAt?: Time;
    adminMessage?: string;
    requestedAt: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DietChart {
    id: string;
    meals: Array<Meal>;
    name: string;
    description: string;
}
export type CreateMemberResult = {
    __kind__: "missingField";
    missingField: {
        fieldName: string;
    };
} | {
    __kind__: "duplicateContactInfo";
    duplicateContactInfo: null;
} | {
    __kind__: "agentError";
    agentError: string;
} | {
    __kind__: "notFound";
    notFound: {
        id: string;
        entity: string;
    };
} | {
    __kind__: "success";
    success: null;
};
export interface MemberProfile {
    id: string;
    finalPayableAmount: bigint;
    status: MembershipStatus;
    contactInfo: string;
    assignedWorkoutId?: string;
    assignedDietId?: string;
    discountAmount: bigint;
    name: string;
    membershipStart: Time;
    membershipEnd: Time;
    packageId: string;
}
export interface VideoMetadata {
    id: string;
    associatedWorkoutId?: string;
    title: string;
    blob: ExternalBlob;
    description: string;
    category: string;
}
export interface MembershipPackage {
    id: string;
    packageType: string;
    durationInMonths: bigint;
    priceInRupees: bigint;
}
export interface AttendanceRecord {
    status: string;
    memberId: string;
    method: AttendanceMethod;
    checkInTime: Time;
    checkOutTime?: Time;
}
export interface UserProfile {
    memberId?: string;
    name: string;
    email: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AttendanceMethod {
    qrScan = "qrScan",
    manualEntry = "manualEntry",
    autoCheckout = "autoCheckout"
}
export enum MembershipStatus {
    active = "active",
    inactive = "inactive",
    paused = "paused"
}
export enum PauseRequestStatus {
    expired = "expired",
    pending = "pending",
    denied = "denied",
    approved = "approved"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addVideo(metadata: VideoMetadata): Promise<void>;
    approvePauseRequest(requestId: string, adminMessage: string | null): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createDietChart(diet: DietChart): Promise<void>;
    createMember(profile: MemberProfile): Promise<CreateMemberResult>;
    createMembershipPackage(pkg: MembershipPackage): Promise<void>;
    createWorkoutChart(workout: WorkoutChart): Promise<void>;
    deleteMembershipPackage(packageId: string): Promise<void>;
    deleteVideo(videoId: string): Promise<void>;
    denyPauseRequest(requestId: string, adminMessage: string | null): Promise<void>;
    getAllDietCharts(): Promise<Array<DietChart>>;
    getAllMembers(): Promise<Array<MemberProfile>>;
    getAllMembershipPackages(): Promise<Array<MembershipPackage>>;
    getAllPauseRequests(): Promise<Array<PauseRequest>>;
    getAllWorkoutCharts(): Promise<Array<WorkoutChart>>;
    getAssignedDiet(memberId: string): Promise<DietChart>;
    getAssignedWorkout(memberId: string): Promise<WorkoutChart>;
    getAttendanceHistory(memberId: string): Promise<Array<AttendanceRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentCheckInStatus(memberId: string): Promise<{
        method?: AttendanceMethod;
        checkInTime?: Time;
        isCheckedIn: boolean;
    } | null>;
    getGymLocation(): Promise<{
        radius: bigint;
        location: LocationCoordinates;
    }>;
    getMemberByContactInfo(contactInfo: string): Promise<MemberProfile | null>;
    getMemberProfile(memberId: string): Promise<MemberProfile>;
    getPauseRequestStatus(memberId: string): Promise<{
        status: PauseRequestStatus;
        requestId: string;
        adminMessage?: string;
    } | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVideoLibrary(memberId: string): Promise<Array<VideoMetadata>>;
    hasPendingPauseRequest(memberId: string): Promise<boolean>;
    healthCheck(): Promise<{
        ok: boolean;
        version: string;
        timestamp: Time;
    }>;
    initiatePauseRequest(memberId: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    processAutoCheckout(memberId: string): Promise<void>;
    recordAttendance(record: AttendanceRecord): Promise<void>;
    recordQRAttendance(memberId: string, isCheckIn: boolean): Promise<void>;
    resumeMembership(memberId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateDietChart(diet: DietChart): Promise<void>;
    updateGymLocation(location: LocationCoordinates, radius: bigint): Promise<void>;
    updateMember(profile: MemberProfile): Promise<void>;
    updateMembershipPackage(pkg: MembershipPackage): Promise<void>;
    updateWorkoutChart(workout: WorkoutChart): Promise<void>;
    validateMemberLogin(memberId: string): Promise<{
        isValid: boolean;
    }>;
}
import type { AttendanceMethod as _AttendanceMethod, AttendanceRecord as _AttendanceRecord, CreateMemberResult as _CreateMemberResult, ExternalBlob as _ExternalBlob, MemberProfile as _MemberProfile, MembershipStatus as _MembershipStatus, PauseRequest as _PauseRequest, PauseRequestStatus as _PauseRequestStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VideoMetadata as _VideoMetadata, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addVideo(arg0: VideoMetadata): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVideo(await to_candid_VideoMetadata_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVideo(await to_candid_VideoMetadata_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async approvePauseRequest(arg0: string, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePauseRequest(arg0, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePauseRequest(arg0, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createDietChart(arg0: DietChart): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDietChart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDietChart(arg0);
            return result;
        }
    }
    async createMember(arg0: MemberProfile): Promise<CreateMemberResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createMember(to_candid_MemberProfile_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CreateMemberResult_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMember(to_candid_MemberProfile_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CreateMemberResult_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async createMembershipPackage(arg0: MembershipPackage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMembershipPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMembershipPackage(arg0);
            return result;
        }
    }
    async createWorkoutChart(arg0: WorkoutChart): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkoutChart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkoutChart(arg0);
            return result;
        }
    }
    async deleteMembershipPackage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMembershipPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMembershipPackage(arg0);
            return result;
        }
    }
    async deleteVideo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async denyPauseRequest(arg0: string, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.denyPauseRequest(arg0, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.denyPauseRequest(arg0, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllDietCharts(): Promise<Array<DietChart>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDietCharts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDietCharts();
            return result;
        }
    }
    async getAllMembers(): Promise<Array<MemberProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembers();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembers();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMembershipPackages(): Promise<Array<MembershipPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembershipPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembershipPackages();
            return result;
        }
    }
    async getAllPauseRequests(): Promise<Array<PauseRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPauseRequests();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPauseRequests();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWorkoutCharts(): Promise<Array<WorkoutChart>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkoutCharts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkoutCharts();
            return result;
        }
    }
    async getAssignedDiet(arg0: string): Promise<DietChart> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignedDiet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignedDiet(arg0);
            return result;
        }
    }
    async getAssignedWorkout(arg0: string): Promise<WorkoutChart> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignedWorkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignedWorkout(arg0);
            return result;
        }
    }
    async getAttendanceHistory(arg0: string): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceHistory(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceHistory(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentCheckInStatus(arg0: string): Promise<{
        method?: AttendanceMethod;
        checkInTime?: Time;
        isCheckedIn: boolean;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentCheckInStatus(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentCheckInStatus(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGymLocation(): Promise<{
        radius: bigint;
        location: LocationCoordinates;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getGymLocation();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGymLocation();
            return result;
        }
    }
    async getMemberByContactInfo(arg0: string): Promise<MemberProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberByContactInfo(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberByContactInfo(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemberProfile(arg0: string): Promise<MemberProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberProfile(arg0);
                return from_candid_MemberProfile_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberProfile(arg0);
            return from_candid_MemberProfile_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPauseRequestStatus(arg0: string): Promise<{
        status: PauseRequestStatus;
        requestId: string;
        adminMessage?: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPauseRequestStatus(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPauseRequestStatus(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoLibrary(arg0: string): Promise<Array<VideoMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoLibrary(arg0);
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoLibrary(arg0);
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasPendingPauseRequest(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasPendingPauseRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasPendingPauseRequest(arg0);
            return result;
        }
    }
    async healthCheck(): Promise<{
        ok: boolean;
        version: string;
        timestamp: Time;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.healthCheck();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.healthCheck();
            return result;
        }
    }
    async initiatePauseRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initiatePauseRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initiatePauseRequest(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async processAutoCheckout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processAutoCheckout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processAutoCheckout(arg0);
            return result;
        }
    }
    async recordAttendance(arg0: AttendanceRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAttendance(to_candid_AttendanceRecord_n52(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAttendance(to_candid_AttendanceRecord_n52(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async recordQRAttendance(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordQRAttendance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordQRAttendance(arg0, arg1);
            return result;
        }
    }
    async resumeMembership(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resumeMembership(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resumeMembership(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n56(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n56(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDietChart(arg0: DietChart): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDietChart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDietChart(arg0);
            return result;
        }
    }
    async updateGymLocation(arg0: LocationCoordinates, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGymLocation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGymLocation(arg0, arg1);
            return result;
        }
    }
    async updateMember(arg0: MemberProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMember(to_candid_MemberProfile_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMember(to_candid_MemberProfile_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateMembershipPackage(arg0: MembershipPackage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMembershipPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMembershipPackage(arg0);
            return result;
        }
    }
    async updateWorkoutChart(arg0: WorkoutChart): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkoutChart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkoutChart(arg0);
            return result;
        }
    }
    async validateMemberLogin(arg0: string): Promise<{
        isValid: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.validateMemberLogin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateMemberLogin(arg0);
            return result;
        }
    }
}
function from_candid_AttendanceMethod_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceMethod): AttendanceMethod {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceRecord_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_CreateMemberResult_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateMemberResult): CreateMemberResult {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_MemberProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberProfile): MemberProfile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_MembershipStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MembershipStatus): MembershipStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PauseRequestStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PauseRequestStatus): PauseRequestStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_PauseRequest_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PauseRequest): PauseRequest {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_VideoMetadata_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoMetadata): Promise<VideoMetadata> {
    return await from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        method: [] | [_AttendanceMethod];
        checkInTime: [] | [_Time];
        isCheckedIn: boolean;
    }]): {
    method?: AttendanceMethod;
    checkInTime?: Time;
    isCheckedIn: boolean;
} | null {
    return value.length === 0 ? null : from_candid_record_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AttendanceMethod]): AttendanceMethod | null {
    return value.length === 0 ? null : from_candid_AttendanceMethod_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MemberProfile]): MemberProfile | null {
    return value.length === 0 ? null : from_candid_MemberProfile_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        status: _PauseRequestStatus;
        requestId: string;
        adminMessage: [] | [string];
    }]): {
    status: PauseRequestStatus;
    requestId: string;
    adminMessage?: string;
} | null {
    return value.length === 0 ? null : from_candid_record_n47(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    finalPayableAmount: bigint;
    status: _MembershipStatus;
    contactInfo: string;
    assignedWorkoutId: [] | [string];
    assignedDietId: [] | [string];
    discountAmount: bigint;
    name: string;
    membershipStart: _Time;
    membershipEnd: _Time;
    packageId: string;
}): {
    id: string;
    finalPayableAmount: bigint;
    status: MembershipStatus;
    contactInfo: string;
    assignedWorkoutId?: string;
    assignedDietId?: string;
    discountAmount: bigint;
    name: string;
    membershipStart: Time;
    membershipEnd: Time;
    packageId: string;
} {
    return {
        id: value.id,
        finalPayableAmount: value.finalPayableAmount,
        status: from_candid_MembershipStatus_n23(_uploadFile, _downloadFile, value.status),
        contactInfo: value.contactInfo,
        assignedWorkoutId: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.assignedWorkoutId)),
        assignedDietId: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.assignedDietId)),
        discountAmount: value.discountAmount,
        name: value.name,
        membershipStart: value.membershipStart,
        membershipEnd: value.membershipEnd,
        packageId: value.packageId
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _PauseRequestStatus;
    memberId: string;
    processedAt: [] | [_Time];
    adminMessage: [] | [string];
    requestedAt: _Time;
}): {
    id: string;
    status: PauseRequestStatus;
    memberId: string;
    processedAt?: Time;
    adminMessage?: string;
    requestedAt: Time;
} {
    return {
        id: value.id,
        status: from_candid_PauseRequestStatus_n29(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId,
        processedAt: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.processedAt)),
        adminMessage: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.adminMessage)),
        requestedAt: value.requestedAt
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    memberId: string;
    method: _AttendanceMethod;
    checkInTime: _Time;
    checkOutTime: [] | [_Time];
}): {
    status: string;
    memberId: string;
    method: AttendanceMethod;
    checkInTime: Time;
    checkOutTime?: Time;
} {
    return {
        status: value.status,
        memberId: value.memberId,
        method: from_candid_AttendanceMethod_n35(_uploadFile, _downloadFile, value.method),
        checkInTime: value.checkInTime,
        checkOutTime: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.checkOutTime))
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberId: [] | [string];
    name: string;
    email: string;
}): {
    memberId?: string;
    name: string;
    email: string;
} {
    return {
        memberId: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.memberId)),
        name: value.name,
        email: value.email
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    method: [] | [_AttendanceMethod];
    checkInTime: [] | [_Time];
    isCheckedIn: boolean;
}): {
    method?: AttendanceMethod;
    checkInTime?: Time;
    isCheckedIn: boolean;
} {
    return {
        method: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.method)),
        checkInTime: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.checkInTime)),
        isCheckedIn: value.isCheckedIn
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PauseRequestStatus;
    requestId: string;
    adminMessage: [] | [string];
}): {
    status: PauseRequestStatus;
    requestId: string;
    adminMessage?: string;
} {
    return {
        status: from_candid_PauseRequestStatus_n29(_uploadFile, _downloadFile, value.status),
        requestId: value.requestId,
        adminMessage: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.adminMessage))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    associatedWorkoutId: [] | [string];
    title: string;
    blob: _ExternalBlob;
    description: string;
    category: string;
}): Promise<{
    id: string;
    associatedWorkoutId?: string;
    title: string;
    blob: ExternalBlob;
    description: string;
    category: string;
}> {
    return {
        id: value.id,
        associatedWorkoutId: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.associatedWorkoutId)),
        title: value.title,
        blob: await from_candid_ExternalBlob_n51(_uploadFile, _downloadFile, value.blob),
        description: value.description,
        category: value.category
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    missingField: {
        fieldName: string;
    };
} | {
    duplicateContactInfo: null;
} | {
    agentError: string;
} | {
    notFound: {
        id: string;
        entity: string;
    };
} | {
    success: null;
}): {
    __kind__: "missingField";
    missingField: {
        fieldName: string;
    };
} | {
    __kind__: "duplicateContactInfo";
    duplicateContactInfo: null;
} | {
    __kind__: "agentError";
    agentError: string;
} | {
    __kind__: "notFound";
    notFound: {
        id: string;
        entity: string;
    };
} | {
    __kind__: "success";
    success: null;
} {
    return "missingField" in value ? {
        __kind__: "missingField",
        missingField: value.missingField
    } : "duplicateContactInfo" in value ? {
        __kind__: "duplicateContactInfo",
        duplicateContactInfo: value.duplicateContactInfo
    } : "agentError" in value ? {
        __kind__: "agentError",
        agentError: value.agentError
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
} | {
    paused: null;
}): MembershipStatus {
    return "active" in value ? MembershipStatus.active : "inactive" in value ? MembershipStatus.inactive : "paused" in value ? MembershipStatus.paused : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expired: null;
} | {
    pending: null;
} | {
    denied: null;
} | {
    approved: null;
}): PauseRequestStatus {
    return "expired" in value ? PauseRequestStatus.expired : "pending" in value ? PauseRequestStatus.pending : "denied" in value ? PauseRequestStatus.denied : "approved" in value ? PauseRequestStatus.approved : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    qrScan: null;
} | {
    manualEntry: null;
} | {
    autoCheckout: null;
}): AttendanceMethod {
    return "qrScan" in value ? AttendanceMethod.qrScan : "manualEntry" in value ? AttendanceMethod.manualEntry : "autoCheckout" in value ? AttendanceMethod.autoCheckout : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MemberProfile>): Array<MemberProfile> {
    return value.map((x)=>from_candid_MemberProfile_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PauseRequest>): Array<PauseRequest> {
    return value.map((x)=>from_candid_PauseRequest_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n33(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoMetadata>): Promise<Array<VideoMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VideoMetadata_n49(_uploadFile, _downloadFile, x)));
}
function to_candid_AttendanceMethod_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceMethod): _AttendanceMethod {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_AttendanceRecord_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceRecord): _AttendanceRecord {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MemberProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberProfile): _MemberProfile {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_MembershipStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipStatus): _MembershipStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_VideoMetadata_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoMetadata): Promise<_VideoMetadata> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    finalPayableAmount: bigint;
    status: MembershipStatus;
    contactInfo: string;
    assignedWorkoutId?: string;
    assignedDietId?: string;
    discountAmount: bigint;
    name: string;
    membershipStart: Time;
    membershipEnd: Time;
    packageId: string;
}): {
    id: string;
    finalPayableAmount: bigint;
    status: _MembershipStatus;
    contactInfo: string;
    assignedWorkoutId: [] | [string];
    assignedDietId: [] | [string];
    discountAmount: bigint;
    name: string;
    membershipStart: _Time;
    membershipEnd: _Time;
    packageId: string;
} {
    return {
        id: value.id,
        finalPayableAmount: value.finalPayableAmount,
        status: to_candid_MembershipStatus_n16(_uploadFile, _downloadFile, value.status),
        contactInfo: value.contactInfo,
        assignedWorkoutId: value.assignedWorkoutId ? candid_some(value.assignedWorkoutId) : candid_none(),
        assignedDietId: value.assignedDietId ? candid_some(value.assignedDietId) : candid_none(),
        discountAmount: value.discountAmount,
        name: value.name,
        membershipStart: value.membershipStart,
        membershipEnd: value.membershipEnd,
        packageId: value.packageId
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    memberId: string;
    method: AttendanceMethod;
    checkInTime: Time;
    checkOutTime?: Time;
}): {
    status: string;
    memberId: string;
    method: _AttendanceMethod;
    checkInTime: _Time;
    checkOutTime: [] | [_Time];
} {
    return {
        status: value.status,
        memberId: value.memberId,
        method: to_candid_AttendanceMethod_n54(_uploadFile, _downloadFile, value.method),
        checkInTime: value.checkInTime,
        checkOutTime: value.checkOutTime ? candid_some(value.checkOutTime) : candid_none()
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberId?: string;
    name: string;
    email: string;
}): {
    memberId: [] | [string];
    name: string;
    email: string;
} {
    return {
        memberId: value.memberId ? candid_some(value.memberId) : candid_none(),
        name: value.name,
        email: value.email
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    associatedWorkoutId?: string;
    title: string;
    blob: ExternalBlob;
    description: string;
    category: string;
}): Promise<{
    id: string;
    associatedWorkoutId: [] | [string];
    title: string;
    blob: _ExternalBlob;
    description: string;
    category: string;
}> {
    return {
        id: value.id,
        associatedWorkoutId: value.associatedWorkoutId ? candid_some(value.associatedWorkoutId) : candid_none(),
        title: value.title,
        blob: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.blob),
        description: value.description,
        category: value.category
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipStatus): {
    active: null;
} | {
    inactive: null;
} | {
    paused: null;
} {
    return value == MembershipStatus.active ? {
        active: null
    } : value == MembershipStatus.inactive ? {
        inactive: null
    } : value == MembershipStatus.paused ? {
        paused: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceMethod): {
    qrScan: null;
} | {
    manualEntry: null;
} | {
    autoCheckout: null;
} {
    return value == AttendanceMethod.qrScan ? {
        qrScan: null
    } : value == AttendanceMethod.manualEntry ? {
        manualEntry: null
    } : value == AttendanceMethod.autoCheckout ? {
        autoCheckout: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
